version: '3'

services:
  web:
    container_name: kirjatkiertoon-web
    build: .
    restart: always
    ports:
      - "80"
    env_file:
      - .prod.env
    depends_on:
      - postgres-db
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.frontend.rule=Host:kirjatkiertoon.fi"

  postgres-db:
    image: "postgres:10.5-alpine"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - kirjatkiertoon-db:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"

volumes:
  kirjatkiertoon-db:
    external: true
